//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlan
    {
        public int IlanId { get; set; }
        public string IlanNo { get; set; }
        public string Aciklama { get; set; }
        public decimal Fiyat { get; set; }
        public string Tarhi { get; set; }
        public int Kilometre { get; set; }
        public string YakitTuru { get; set; }
        public string ModelYili { get; set; }
        public string VitesTuru { get; set; }
        public string Username { get; set; }
        public string Telefon { get; set; }
        public int DurumId { get; set; }
        public int MarkaId { get; set; }
        public int ModelId { get; set; }
        public int SehirId { get; set; }
    }
}
